# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=400)),
                ('workout', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
